// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fruabamwicpfdhmykbol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZydWFiYW13aWNwZmRobXlrYm9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODM3MzQsImV4cCI6MjA2NjM1OTczNH0.xRh2ZOjtrecfD6ykFvzKPwuQAxwfY6mGlltxEZ2pVbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);